allPath = {'cwdPath': {'All': {'comment': 'C:/Users/ben/AppData/Local/Programs/Python/Python311/Scripts/',
                     'py': 3}},
 'inputPath': {'All': {'comment': 'C:/Users/ben/OneDrive/Documents/Gaba_Docs/development/Python/Python_Ben/pgmInput/',
                       'py': 3}},
 'logPath': {'All': {'comment': 'C:/Users/ben/OneDrive/Documents/Gaba_Docs/development/Python/Python_Ben/logs/',
                     'py': 3}},
 'modulePath': {'All': {'comment': 'C:/Users/ben/OneDrive/Documents/Gaba_Docs/development/Python/Python_Ben/module/',
                        'py': 3}},
 'myPyPath': {'All': {'comment': 'C:/Users/ben/OneDrive/Documents/Gaba_Docs/development/Python/Python_Ben/',
                      'py': 3},
              'Excel': {'comment': 'C:/Users/ben/OneDrive/Documents/Gaba_Docs/development/Python/Python_Ben/Excel/',
                        'py': 3},
              'partTwo_Automation': {'comment': 'C:/Users/ben/OneDrive/Documents/Gaba_Docs/development/Python/Python_Ben/partTwo_Automation/',
                                     'py': 3},
              'partTwo_WebScraping': {'comment': 'C:/Users/ben/OneDrive/Documents/Gaba_Docs/development/Python/Python_Ben/partTwo_WebScraping/',
                                      'py': 3}},
 'outputPath': {'All': {'comment': 'C:/Users/ben/OneDrive/Documents/Gaba_Docs/development/Python/Python_Ben/pgmOutput/',
                        'py': 3}},
 'pipPath': {'All': {'comment': 'C:/Users/ben/AppData/Local/Programs/Python/Python311/Scripts/',
                     'py': 3}}}